name: deploy FH
on:
  push:
    branches: [ master, main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn build
      - run: aws s3 sync build s3://falseheather.john-shenk.com
      - run: aws cloudfront create-invalidation --paths /index.html --distribution-id E1E62A9GMK3VFM
